name: cetools-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh=3.1.1
  - panel=1.0.2
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - openpyxl
  - netCDF4
  - pip
  - pip:
      - -e ./src          # installs CEtools package from the src/ folder
